model_name: unet
parametrization: eps
noise_schedule_type: cosine
unet_config:
  freq_shift: 1
  flip_sin_to_cos: false
  down_block_types:
    - DownBlock2D
    - AttnDownBlock2D
    - DownBlock2D
    - DownBlock2D
  up_block_types:
    - UpBlock2D
    - UpBlock2D
    - AttnUpBlock2D
    - UpBlock2D
  block_out_channels:
    - 128
    - 256
    - 256
    - 256
  downsample_padding: 0
  attention_head_dim: 64
  dropout: 0.1
  norm_eps: 1e-06
